/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_EVENTARRAY_PB_H_INCLUDED
#define PB_EVENTARRAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Array of events message format
The array of events then represented in proto3 with repeated keyword, this means that 
the EventArray message object can contain any number of GenericEvent objects */
typedef struct _EventArray { 
    pb_callback_t event_message; 
} EventArray;

/* 0x01 - New movement pattern detected */
typedef struct _Event0x01 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
    uint32_t pattern_id; 
} Event0x01;

/* 0x02 - Mop change detected */
typedef struct _Event0x02 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
    uint32_t mop_id; 
} Event0x02;

/* 0x04 - Another room detected */
typedef struct _Event0x04 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
    uint32_t room_id; 
} Event0x04;

/* 0x05 - Wrong mop is used in the room */
typedef struct _Event0x05 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
    uint32_t room_id; 
    uint32_t mop_id; 
} Event0x05;

/* 0x06 - Same mop used in another room */
typedef struct _Event0x06 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
    uint32_t room_id; 
    uint32_t mop_id; 
} Event0x06;

/* 0x07 - New location detected */
typedef struct _Event0x07 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
    pb_callback_t location_epc; 
} Event0x07;

/* 0x09 - Battery charge low */
typedef struct _Event0x09 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
} Event0x09;

/* 0x0B - Connection up */
typedef struct _Event0x0B { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
} Event0x0B;

/* 0x0C - Connection down */
typedef struct _Event0x0C { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
} Event0x0C;

/* 0x0D - Button pressed */
typedef struct _Event0x0D { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
} Event0x0D;

/* 0x0F - USB plugged in */
typedef struct _Event0x0F { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
} Event0x0F;

/* 0x10 - USB plugged off */
typedef struct _Event0x10 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
} Event0x10;

/* 0x11 - Charging started */
typedef struct _Event0x11 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
} Event0x11;

/* 0x12 - Charging stopped */
typedef struct _Event0x12 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
} Event0x12;

/* 0x13 - Power on */
typedef struct _Event0x13 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
} Event0x13;

/* 0x17 - Hit shock */
typedef struct _Event0x17 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
    uint32_t schock_acc; 
} Event0x17;

/* 0x18 - Frame side flip */
typedef struct _Event0x18 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
    uint32_t frame_side; 
} Event0x18;

/* 0x19 - Inappropriate mop is used in the room in mopping state */
typedef struct _Event0x19 { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
    uint32_t room_id; 
    uint32_t mop_id; 
} Event0x19;

/* 0x1A - Inappropriate mop is near the room */
typedef struct _Event0x1A { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
    uint32_t room_id; 
    uint32_t mop_id; 
} Event0x1A;

/* 0x1B - Mop change */
typedef struct _Event0x1B { 
    uint32_t event_id; 
    uint64_t event_timestamp; 
} Event0x1B;

/* Generic unified message format
As specified in proto3 Oneof definition, we use oneof object to unify the event message objects: */
typedef struct _GenericEvent { 
    pb_size_t which_OneOfGenericEvent;
    union {
        Event0x01 field_event0x01;
        Event0x02 field_event0x02;
        Event0x04 field_event0x04;
        Event0x05 field_event0x05;
        Event0x06 field_event0x06;
        Event0x07 field_event0x07;
        Event0x09 field_event0x09;
        Event0x0B field_event0x0B;
        Event0x0C field_event0x0C;
        Event0x0D field_event0x0D;
        Event0x0F field_event0x0F;
        Event0x10 field_event0x10;
        Event0x11 field_event0x11;
        Event0x12 field_event0x12;
        Event0x13 field_event0x13;
        Event0x17 field_event0x17;
        Event0x18 field_event0x18;
    } OneOfGenericEvent; 
} GenericEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GenericEvent_init_default                {0, {Event0x01_init_default}}
#define EventArray_init_default                  {{{NULL}, NULL}}
#define Event0x01_init_default                   {0, 0, 0}
#define Event0x02_init_default                   {0, 0, 0}
#define Event0x04_init_default                   {0, 0, 0}
#define Event0x05_init_default                   {0, 0, 0, 0}
#define Event0x06_init_default                   {0, 0, 0, 0}
#define Event0x07_init_default                   {0, 0, {{NULL}, NULL}}
#define Event0x09_init_default                   {0, 0}
#define Event0x0B_init_default                   {0, 0}
#define Event0x0C_init_default                   {0, 0}
#define Event0x0D_init_default                   {0, 0}
#define Event0x0F_init_default                   {0, 0}
#define Event0x10_init_default                   {0, 0}
#define Event0x11_init_default                   {0, 0}
#define Event0x12_init_default                   {0, 0}
#define Event0x13_init_default                   {0, 0}
#define Event0x17_init_default                   {0, 0, 0}
#define Event0x18_init_default                   {0, 0, 0}
#define Event0x19_init_default                   {0, 0, 0, 0}
#define Event0x1A_init_default                   {0, 0, 0, 0}
#define Event0x1B_init_default                   {0, 0}
#define GenericEvent_init_zero                   {0, {Event0x01_init_zero}}
#define EventArray_init_zero                     {{{NULL}, NULL}}
#define Event0x01_init_zero                      {0, 0, 0}
#define Event0x02_init_zero                      {0, 0, 0}
#define Event0x04_init_zero                      {0, 0, 0}
#define Event0x05_init_zero                      {0, 0, 0, 0}
#define Event0x06_init_zero                      {0, 0, 0, 0}
#define Event0x07_init_zero                      {0, 0, {{NULL}, NULL}}
#define Event0x09_init_zero                      {0, 0}
#define Event0x0B_init_zero                      {0, 0}
#define Event0x0C_init_zero                      {0, 0}
#define Event0x0D_init_zero                      {0, 0}
#define Event0x0F_init_zero                      {0, 0}
#define Event0x10_init_zero                      {0, 0}
#define Event0x11_init_zero                      {0, 0}
#define Event0x12_init_zero                      {0, 0}
#define Event0x13_init_zero                      {0, 0}
#define Event0x17_init_zero                      {0, 0, 0}
#define Event0x18_init_zero                      {0, 0, 0}
#define Event0x19_init_zero                      {0, 0, 0, 0}
#define Event0x1A_init_zero                      {0, 0, 0, 0}
#define Event0x1B_init_zero                      {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define EventArray_event_message_tag             1
#define Event0x01_event_id_tag                   1
#define Event0x01_event_timestamp_tag            2
#define Event0x01_pattern_id_tag                 3
#define Event0x02_event_id_tag                   1
#define Event0x02_event_timestamp_tag            2
#define Event0x02_mop_id_tag                     3
#define Event0x04_event_id_tag                   1
#define Event0x04_event_timestamp_tag            2
#define Event0x04_room_id_tag                    3
#define Event0x05_event_id_tag                   1
#define Event0x05_event_timestamp_tag            2
#define Event0x05_room_id_tag                    3
#define Event0x05_mop_id_tag                     4
#define Event0x06_event_id_tag                   1
#define Event0x06_event_timestamp_tag            2
#define Event0x06_room_id_tag                    3
#define Event0x06_mop_id_tag                     4
#define Event0x07_event_id_tag                   1
#define Event0x07_event_timestamp_tag            2
#define Event0x07_location_epc_tag               3
#define Event0x09_event_id_tag                   1
#define Event0x09_event_timestamp_tag            2
#define Event0x0B_event_id_tag                   1
#define Event0x0B_event_timestamp_tag            2
#define Event0x0C_event_id_tag                   1
#define Event0x0C_event_timestamp_tag            2
#define Event0x0D_event_id_tag                   1
#define Event0x0D_event_timestamp_tag            2
#define Event0x0F_event_id_tag                   1
#define Event0x0F_event_timestamp_tag            2
#define Event0x10_event_id_tag                   1
#define Event0x10_event_timestamp_tag            2
#define Event0x11_event_id_tag                   1
#define Event0x11_event_timestamp_tag            2
#define Event0x12_event_id_tag                   1
#define Event0x12_event_timestamp_tag            2
#define Event0x13_event_id_tag                   1
#define Event0x13_event_timestamp_tag            2
#define Event0x17_event_id_tag                   1
#define Event0x17_event_timestamp_tag            2
#define Event0x17_schock_acc_tag                 3
#define Event0x18_event_id_tag                   1
#define Event0x18_event_timestamp_tag            2
#define Event0x18_frame_side_tag                 3
#define Event0x19_event_id_tag                   1
#define Event0x19_event_timestamp_tag            2
#define Event0x19_room_id_tag                    3
#define Event0x19_mop_id_tag                     4
#define Event0x1A_event_id_tag                   1
#define Event0x1A_event_timestamp_tag            2
#define Event0x1A_room_id_tag                    3
#define Event0x1A_mop_id_tag                     4
#define Event0x1B_event_id_tag                   1
#define Event0x1B_event_timestamp_tag            2
#define GenericEvent_field_event0x01_tag         1
#define GenericEvent_field_event0x02_tag         2
#define GenericEvent_field_event0x04_tag         3
#define GenericEvent_field_event0x05_tag         4
#define GenericEvent_field_event0x06_tag         5
#define GenericEvent_field_event0x07_tag         6
#define GenericEvent_field_event0x09_tag         7
#define GenericEvent_field_event0x0B_tag         8
#define GenericEvent_field_event0x0C_tag         9
#define GenericEvent_field_event0x0D_tag         10
#define GenericEvent_field_event0x0F_tag         11
#define GenericEvent_field_event0x10_tag         12
#define GenericEvent_field_event0x11_tag         13
#define GenericEvent_field_event0x12_tag         14
#define GenericEvent_field_event0x13_tag         15
#define GenericEvent_field_event0x17_tag         16
#define GenericEvent_field_event0x18_tag         17

/* Struct field encoding specification for nanopb */
#define GenericEvent_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x01,OneOfGenericEvent.field_event0x01),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x02,OneOfGenericEvent.field_event0x02),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x04,OneOfGenericEvent.field_event0x04),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x05,OneOfGenericEvent.field_event0x05),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x06,OneOfGenericEvent.field_event0x06),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x07,OneOfGenericEvent.field_event0x07),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x09,OneOfGenericEvent.field_event0x09),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x0B,OneOfGenericEvent.field_event0x0B),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x0C,OneOfGenericEvent.field_event0x0C),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x0D,OneOfGenericEvent.field_event0x0D),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x0F,OneOfGenericEvent.field_event0x0F),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x10,OneOfGenericEvent.field_event0x10),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x11,OneOfGenericEvent.field_event0x11),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x12,OneOfGenericEvent.field_event0x12),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x13,OneOfGenericEvent.field_event0x13),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x17,OneOfGenericEvent.field_event0x17),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (OneOfGenericEvent,field_event0x18,OneOfGenericEvent.field_event0x18),  17)
#define GenericEvent_CALLBACK NULL
#define GenericEvent_DEFAULT NULL
#define GenericEvent_OneOfGenericEvent_field_event0x01_MSGTYPE Event0x01
#define GenericEvent_OneOfGenericEvent_field_event0x02_MSGTYPE Event0x02
#define GenericEvent_OneOfGenericEvent_field_event0x04_MSGTYPE Event0x04
#define GenericEvent_OneOfGenericEvent_field_event0x05_MSGTYPE Event0x05
#define GenericEvent_OneOfGenericEvent_field_event0x06_MSGTYPE Event0x06
#define GenericEvent_OneOfGenericEvent_field_event0x07_MSGTYPE Event0x07
#define GenericEvent_OneOfGenericEvent_field_event0x09_MSGTYPE Event0x09
#define GenericEvent_OneOfGenericEvent_field_event0x0B_MSGTYPE Event0x0B
#define GenericEvent_OneOfGenericEvent_field_event0x0C_MSGTYPE Event0x0C
#define GenericEvent_OneOfGenericEvent_field_event0x0D_MSGTYPE Event0x0D
#define GenericEvent_OneOfGenericEvent_field_event0x0F_MSGTYPE Event0x0F
#define GenericEvent_OneOfGenericEvent_field_event0x10_MSGTYPE Event0x10
#define GenericEvent_OneOfGenericEvent_field_event0x11_MSGTYPE Event0x11
#define GenericEvent_OneOfGenericEvent_field_event0x12_MSGTYPE Event0x12
#define GenericEvent_OneOfGenericEvent_field_event0x13_MSGTYPE Event0x13
#define GenericEvent_OneOfGenericEvent_field_event0x17_MSGTYPE Event0x17
#define GenericEvent_OneOfGenericEvent_field_event0x18_MSGTYPE Event0x18

#define EventArray_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  event_message,     1)
#define EventArray_CALLBACK pb_default_field_callback
#define EventArray_DEFAULT NULL
#define EventArray_event_message_MSGTYPE GenericEvent

#define Event0x01_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2) \
X(a, STATIC,   SINGULAR, UINT32,   pattern_id,        3)
#define Event0x01_CALLBACK NULL
#define Event0x01_DEFAULT NULL

#define Event0x02_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2) \
X(a, STATIC,   SINGULAR, UINT32,   mop_id,            3)
#define Event0x02_CALLBACK NULL
#define Event0x02_DEFAULT NULL

#define Event0x04_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2) \
X(a, STATIC,   SINGULAR, UINT32,   room_id,           3)
#define Event0x04_CALLBACK NULL
#define Event0x04_DEFAULT NULL

#define Event0x05_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2) \
X(a, STATIC,   SINGULAR, UINT32,   room_id,           3) \
X(a, STATIC,   SINGULAR, UINT32,   mop_id,            4)
#define Event0x05_CALLBACK NULL
#define Event0x05_DEFAULT NULL

#define Event0x06_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2) \
X(a, STATIC,   SINGULAR, UINT32,   room_id,           3) \
X(a, STATIC,   SINGULAR, UINT32,   mop_id,            4)
#define Event0x06_CALLBACK NULL
#define Event0x06_DEFAULT NULL

#define Event0x07_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2) \
X(a, CALLBACK, SINGULAR, BYTES,    location_epc,      3)
#define Event0x07_CALLBACK pb_default_field_callback
#define Event0x07_DEFAULT NULL

#define Event0x09_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2)
#define Event0x09_CALLBACK NULL
#define Event0x09_DEFAULT NULL

#define Event0x0B_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2)
#define Event0x0B_CALLBACK NULL
#define Event0x0B_DEFAULT NULL

#define Event0x0C_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2)
#define Event0x0C_CALLBACK NULL
#define Event0x0C_DEFAULT NULL

#define Event0x0D_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2)
#define Event0x0D_CALLBACK NULL
#define Event0x0D_DEFAULT NULL

#define Event0x0F_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2)
#define Event0x0F_CALLBACK NULL
#define Event0x0F_DEFAULT NULL

#define Event0x10_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2)
#define Event0x10_CALLBACK NULL
#define Event0x10_DEFAULT NULL

#define Event0x11_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2)
#define Event0x11_CALLBACK NULL
#define Event0x11_DEFAULT NULL

#define Event0x12_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2)
#define Event0x12_CALLBACK NULL
#define Event0x12_DEFAULT NULL

#define Event0x13_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2)
#define Event0x13_CALLBACK NULL
#define Event0x13_DEFAULT NULL

#define Event0x17_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2) \
X(a, STATIC,   SINGULAR, UINT32,   schock_acc,        3)
#define Event0x17_CALLBACK NULL
#define Event0x17_DEFAULT NULL

#define Event0x18_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2) \
X(a, STATIC,   SINGULAR, UINT32,   frame_side,        3)
#define Event0x18_CALLBACK NULL
#define Event0x18_DEFAULT NULL

#define Event0x19_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2) \
X(a, STATIC,   SINGULAR, UINT32,   room_id,           3) \
X(a, STATIC,   SINGULAR, UINT32,   mop_id,            4)
#define Event0x19_CALLBACK NULL
#define Event0x19_DEFAULT NULL

#define Event0x1A_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2) \
X(a, STATIC,   SINGULAR, UINT32,   room_id,           3) \
X(a, STATIC,   SINGULAR, UINT32,   mop_id,            4)
#define Event0x1A_CALLBACK NULL
#define Event0x1A_DEFAULT NULL

#define Event0x1B_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_id,          1) \
X(a, STATIC,   SINGULAR, UINT64,   event_timestamp,   2)
#define Event0x1B_CALLBACK NULL
#define Event0x1B_DEFAULT NULL

extern const pb_msgdesc_t GenericEvent_msg;
extern const pb_msgdesc_t EventArray_msg;
extern const pb_msgdesc_t Event0x01_msg;
extern const pb_msgdesc_t Event0x02_msg;
extern const pb_msgdesc_t Event0x04_msg;
extern const pb_msgdesc_t Event0x05_msg;
extern const pb_msgdesc_t Event0x06_msg;
extern const pb_msgdesc_t Event0x07_msg;
extern const pb_msgdesc_t Event0x09_msg;
extern const pb_msgdesc_t Event0x0B_msg;
extern const pb_msgdesc_t Event0x0C_msg;
extern const pb_msgdesc_t Event0x0D_msg;
extern const pb_msgdesc_t Event0x0F_msg;
extern const pb_msgdesc_t Event0x10_msg;
extern const pb_msgdesc_t Event0x11_msg;
extern const pb_msgdesc_t Event0x12_msg;
extern const pb_msgdesc_t Event0x13_msg;
extern const pb_msgdesc_t Event0x17_msg;
extern const pb_msgdesc_t Event0x18_msg;
extern const pb_msgdesc_t Event0x19_msg;
extern const pb_msgdesc_t Event0x1A_msg;
extern const pb_msgdesc_t Event0x1B_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GenericEvent_fields &GenericEvent_msg
#define EventArray_fields &EventArray_msg
#define Event0x01_fields &Event0x01_msg
#define Event0x02_fields &Event0x02_msg
#define Event0x04_fields &Event0x04_msg
#define Event0x05_fields &Event0x05_msg
#define Event0x06_fields &Event0x06_msg
#define Event0x07_fields &Event0x07_msg
#define Event0x09_fields &Event0x09_msg
#define Event0x0B_fields &Event0x0B_msg
#define Event0x0C_fields &Event0x0C_msg
#define Event0x0D_fields &Event0x0D_msg
#define Event0x0F_fields &Event0x0F_msg
#define Event0x10_fields &Event0x10_msg
#define Event0x11_fields &Event0x11_msg
#define Event0x12_fields &Event0x12_msg
#define Event0x13_fields &Event0x13_msg
#define Event0x17_fields &Event0x17_msg
#define Event0x18_fields &Event0x18_msg
#define Event0x19_fields &Event0x19_msg
#define Event0x1A_fields &Event0x1A_msg
#define Event0x1B_fields &Event0x1B_msg

/* Maximum encoded size of messages (where known) */
/* GenericEvent_size depends on runtime parameters */
/* EventArray_size depends on runtime parameters */
/* Event0x07_size depends on runtime parameters */
#define Event0x01_size                           23
#define Event0x02_size                           23
#define Event0x04_size                           23
#define Event0x05_size                           29
#define Event0x06_size                           29
#define Event0x09_size                           17
#define Event0x0B_size                           17
#define Event0x0C_size                           17
#define Event0x0D_size                           17
#define Event0x0F_size                           17
#define Event0x10_size                           17
#define Event0x11_size                           17
#define Event0x12_size                           17
#define Event0x13_size                           17
#define Event0x17_size                           23
#define Event0x18_size                           23
#define Event0x19_size                           29
#define Event0x1A_size                           29
#define Event0x1B_size                           17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
